import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "My Skills",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col justify-center">
      {children}
    </div>
  );
}
