import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/blocks/Header/Header";
import Footer from "@/components/blocks/Footer/Footer";

export const metadata: Metadata = {
  title: "My Skills",
  description: "Generated by create next app",
};

export default function PlatformLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
        <Header />
          {children}
        <Footer />
    </div>
  );
}
